name: Daily Bitcoin Watchdog Run

on:
  schedule:
    - cron: '0 21 * * *'  # Runs at 21:00 UTC daily
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-watchdog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
        
    - name: Run Watchdog
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: java -jar target/bitcoin-watchdog.jar
