name: Daily Bitcoin Watchdog Run

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  run-watchdog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
        
    - name: Print Environment Variables (masked)
      run: |
        echo "Email username is configured: ${{ secrets.EMAIL_USERNAME != '' }}"
        echo "Email password is configured: ${{ secrets.EMAIL_PASSWORD != '' }}"
        
    - name: Run Watchdog
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        echo "Starting application..."
        java -jar target/bitcoin-watchdog.jar
        echo "Application finished"

    - name: Check application logs
      if: always()
      run: |
        echo "Checking for log files..."
        ls -la
        if [ -f "application.log" ]; then
          echo "Application log contents:"
          cat application.log
        fi
