name: Daily Bitcoin Watchdog Run

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  run-watchdog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
        
    - name: List target directory
      run: |
        echo "Contents of target directory:"
        ls -la target/
        
    - name: Find JAR file
      run: |
        echo "Looking for JAR files:"
        find . -name "*.jar"
        
    - name: Run Watchdog
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        JAR_FILE=$(find target/ -name "*.jar" ! -name "*sources.jar" ! -name "*javadoc.jar" | head -1)
        echo "Found JAR file: $JAR_FILE"
        java -jar "$JAR_FILE"
